In [229]:
import pandas as pd

In [230]:
customers = pd.read_csv(r'C:\Users\LENOVO\OneDrive\Desktop\aceets\customers_dataset.csv')
orders = pd.read_csv(r'C:\Users\LENOVO\OneDrive\Desktop\aceets\orders_dataset.csv')
products = pd.read_csv(r'C:\Users\LENOVO\OneDrive\Desktop\aceets\products_dataset.csv')
returns = pd.read_csv(r'C:\Users\LENOVO\OneDrive\Desktop\aceets\returns_dataset.csv')

In [231]:
customers.head()

  customer_id   customer_name       city        state signup_date
0  CUST-10000      john Singh  Ahmedabad      Gujarat  2023-04-15
1  CUST-10001     Sarah Brown     Mumbai  Maharashtra  2024-09-08
2  CUST-10002      Amit Brown       Pune  Maharashtra  2023-10-12
3  CUST-10003  Jessica Sharma    Kolkata  West Bengal  2023-12-11
4  CUST-10004     Sneha Patel    Chennai   Tamil Nadu  2024-04-15

In [232]:
customers.tail()

      customer_id customer_name       city        state signup_date
15295  CUST-14665  Shreya Smith  Bengaluru    Karnataka  2024-08-12
15296  CUST-19604  Kavita Kumar    Chennai   Tamil Nadu  2024-05-22
15297  CUST-16550   Sarah Reddy     Jaipur    Rajasthan  2023-02-09
15298  CUST-10286     MEERA Das    Kolkata  West Bengal  2023-12-04
15299  CUST-23775   Arjun Smith      Patna        bihar  2024-11-19

In [233]:
customers.shape

(15300, 5)

In [234]:
customers.describe()

       customer_id customer_name       city        state signup_date
count        15300         15300      15300        15300       15300
unique       15000          1448         13           33         701
top     CUST-10088  Aditya Mehta  Bengaluru  Maharashtra  2023-06-29
freq             2            40       1249         2110          36

In [235]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 15300 entries, 0 to 15299
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    15300 non-null  str
 1   customer_name  15300 non-null  str
 2   city           15300 non-null  str
 3   state          15300 non-null  str
 4   signup_date    15300 non-null  str
dtypes: str(5)
memory usage: 597.8 KB

In [236]:
customers.columns

Index(['customer_id', 'customer_name', 'city', 'state', 'signup_date'], dtype='str')

In [237]:
customers.isnull().sum()

customer_id      0
customer_name    0
city             0
state            0
signup_date      0
dtype: int64

In [238]:
customers.duplicated().sum()

np.int64(300)

In [239]:
customers = customers.drop_duplicates()

In [240]:
customers.duplicated().sum()

np.int64(0)

In [241]:
customers['customer_id'].unique

<bound method Series.unique of 0        CUST-10000
1        CUST-10001
2        CUST-10002
3        CUST-10003
4        CUST-10004
            ...
14995    CUST-24995
14996    CUST-24996
14997    CUST-24997
14998    CUST-24998
14999    CUST-24999
Name: customer_id, Length: 15000, dtype: str>

In [242]:
customers['customer_name'].value_counts()

customer_name
Aditya Mehta     38
Aditya Roy       37
Sanjay Taylor    37
David Mehta      35
Sarah Patel      35
                 ..
ALEX Smith        1
JESSICA Reddy     1
karan Nair        1
SARAH Patel       1
PRIYA Gupta       1
Name: count, Length: 1448, dtype: int64

In [243]:
customers['city'].value_counts()

city
Bengaluru     1227
Kolkata       1206
Pune          1182
Mumbai        1170
Delhi         1158
Chennai       1152
Chandigarh    1150
Lucknow       1147
Surat         1141
Hyderabad     1135
Jaipur        1115
Patna         1112
Ahmedabad     1105
Name: count, dtype: int64

In [244]:
customers['state'].value_counts()

state
Maharashtra      2068
Gujarat          1965
Karnataka        1093
West Bengal      1042
Delhi            1024
Tamil Nadu       1020
Uttar Pradesh    1008
Punjab           1007
Telangana         997
Rajasthan         985
Bihar             979
gujarat           184
maharashtra       170
MAHARASHTRA       114
west bengal       111
GUJARAT            97
punjab             90
bihar              90
rajasthan          87
delhi              84
telangana          84
karnataka          80
uttar pradesh      77
tamil nadu         76
UTTAR PRADESH      62
TAMIL NADU         56
KARNATAKA          54
TELANGANA          54
PUNJAB             53
WEST BENGAL        53
DELHI              50
BIHAR              43
RAJASTHAN          43
Name: count, dtype: int64

In [245]:
text_col = [
    'customer_name',
    'state'
]

for col in text_col:
    customers[col] = customers[col].str.title()

In [246]:
text_col = [
    'customer_name',
    'state'
]

for col in text_col:
    customers[col] = customers[col].str.replace(' ', '_')

In [247]:
customers['state'].value_counts()

state
Maharashtra      2352
Gujarat          2246
Karnataka        1227
West_Bengal      1206
Delhi            1158
Tamil_Nadu       1152
Punjab           1150
Uttar_Pradesh    1147
Telangana        1135
Rajasthan        1115
Bihar            1112
Name: count, dtype: int64

In [248]:
customers['customer_name'].value_counts()

customer_name
Aditya_Mehta     40
Meera_Kumar      40
Sanjay_Taylor    40
Kavita_Bhasin    39
David_Mehta      38
                 ..
Karan_Gupta      13
Emma_Gupta       13
Jessica_Verma    12
Sanjay_Das       11
Arjun_Brown      11
Name: count, Length: 600, dtype: int64

In [249]:
customers['signup_date'].dtype

In [250]:
customers['signup_date'] = pd.to_datetime(customers['signup_date'])

In [251]:
customers['signup_date'].dtype

dtype('<M8[us]')

In [252]:
customers.duplicated().sum()

np.int64(0)

In [253]:
customers.columns

Index(['customer_id', 'customer_name', 'city', 'state', 'signup_date'], dtype='str')

In [254]:
customers.columns = customers.columns.str.title()

In [255]:
customers.head()

  Customer_Id   Customer_Name       City        State Signup_Date
0  CUST-10000      John_Singh  Ahmedabad      Gujarat  2023-04-15
1  CUST-10001     Sarah_Brown     Mumbai  Maharashtra  2024-09-08
2  CUST-10002      Amit_Brown       Pune  Maharashtra  2023-10-12
3  CUST-10003  Jessica_Sharma    Kolkata  West_Bengal  2023-12-11
4  CUST-10004     Sneha_Patel    Chennai   Tamil_Nadu  2024-04-15

In [256]:
customers.tail()

      Customer_Id   Customer_Name        City       State Signup_Date
14995  CUST-24995   Jessica_Kumar     Chennai  Tamil_Nadu  2024-02-20
14996  CUST-24996       Sarah_Rao  Chandigarh      Punjab  2023-12-28
14997  CUST-24997    Shreya_Reddy      Jaipur   Rajasthan  2024-01-15
14998  CUST-24998     Arjun_Gupta       Surat     Gujarat  2024-01-08
14999  CUST-24999  Aditya_Johnson     Chennai  Tamil_Nadu  2024-02-18

In [257]:
customers.describe()

                      Signup_Date
count                       15000
mean   2023-12-20 02:35:02.400000
min           2023-01-01 00:00:00
25%           2023-06-26 18:00:00
50%           2023-12-24 00:00:00
75%           2024-06-12 00:00:00
max           2024-12-01 00:00:00

In [258]:
customers.shape

(15000, 5)

In [259]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_Id    15000 non-null  str
 1   Customer_Name  15000 non-null  str
 2   City           15000 non-null  str
 3   State          15000 non-null  str
 4   Signup_Date    15000 non-null  datetime64[us]
dtypes: datetime64[us](1), str(4)
memory usage: 586.1 KB

In [260]:
orders.head()

,order_id,order_date,customer_id,product_id,quantity,discount,payment_method,ship_mode,sales_amount
0,ORD-100000,2024-07-22,CUST-10001,PROD-151,4,0.00,Cash on Delivery,same day,2423.32
1,ORD-100001,2024-10-12,CUST-10003,PROD-243,3,0.10,cod,Standard,2145.02
2,ORD-100002,02-28-2024,CUST-10002,PROD-262,1,0.00,Cash on Delivery,same day,891.12
3,ORD-100003,2024-12-21,CUST-10007,PROD-292,4,0.15,cod,Same Day,3328.70
4,ORD-100004,26/04/2024,CUST-10004,PROD-274,1,0.00,COD,Second Class,580.50

In [261]:
orders.tail()

,order_id,order_date,customer_id,product_id,quantity,discount,payment_method,ship_mode,sales_amount
155842,ORD-111567,04-27-2024,CUST-10002,PROD-158,2,0.00,Cash on Delivery,same day,1146.64
155843,ORD-198767,07/05/2024,CUST-19446,PROD-242,2,0.10,Credit Card,same day,1311.77
155844,ORD-157770,2024-12-21,CUST-20960,PROD-117,3,0.00,cod,Standard Class,859.53
155845,ORD-104468,2024-02-16,CUST-10009,PROD-261,3,0.25,UPI,Standard Class,420.07
155846,ORD-185986,14/06/2024,CUST-12066,PROD-196,2,0.05,credit card,Same Day,1433.74

In [262]:
orders.shape

(155847, 9)

In [263]:
orders.isnull().sum()

order_id             0
order_date           0
customer_id          0
product_id           0
quantity             0
discount             0
payment_method    2338
ship_mode         3117
sales_amount         0
dtype: int64

In [264]:
orders.duplicated().sum()

np.int64(1098)

In [265]:
orders = orders.drop_duplicates()

In [266]:
orders.duplicated().sum()

np.int64(0)

In [267]:
orders['order_id'].unique

<bound method Series.unique of 0         ORD-100000
1         ORD-100001
2         ORD-100002
3         ORD-100003
4         ORD-100004
             ...
155785    ORD-110045
155793    ORD-101313
155814    ORD-103742
155825    ORD-200060
155826    ORD-150811
Name: order_id, Length: 154749, dtype: str>

In [268]:
orders['order_date'].dtype

In [269]:
orders['order_date'] = pd.to_datetime(
    orders['order_date'],
    format='mixed',
    errors='coerce'
)

In [270]:
orders['order_date'].dtype

dtype('<M8[us]')

In [271]:
orders['quantity'].unique

<bound method Series.unique of 0         4
1         3
2         1
3         4
4         1
         ..
155785    1
155793    1
155814    4
155825    5
155826    5
Name: quantity, Length: 154749, dtype: int64>

In [272]:
orders[orders['quantity'] < 0]

Empty DataFrame
Columns: [order_id, order_date, customer_id, product_id, quantity, discount, payment_method, ship_mode, sales_amount]
Index: []

In [273]:
orders[orders['discount'] < 0]

Empty DataFrame
Columns: [order_id, order_date, customer_id, product_id, quantity, discount, payment_method, ship_mode, sales_amount]
Index: []

In [274]:
text_col = [
    'payment_method',
    'ship_mode'
]

for col in text_col:
    orders[col] = orders[col].fillna('Unknown')

In [275]:
orders.isnull().sum()

order_id          0
order_date        0
customer_id       0
product_id        0
quantity          0
discount          0
payment_method    0
ship_mode         0
sales_amount      0
dtype: int64

In [276]:
orders['payment_method'].value_counts()

payment_method
cod                 17061
UPI                 17026
Net Banking         16957
credit card         16941
Debit Card          16936
Cash on Delivery    16930
upi                 16901
COD                 16836
Credit Card         16823
Unknown              2338
Name: count, dtype: int64

In [277]:
orders['ship_mode'].value_counts()

ship_mode
Second Class      25456
Standard Class    25344
Same Day          25320
Standard          25214
same day          25210
First Class       25088
Unknown            3117
Name: count, dtype: int64

In [278]:
text_col = [
    'payment_method',
    'ship_mode'
]

for col in text_col:
    orders[col] = orders[col].str.title()

In [279]:
text_col = [
    'payment_method',
    'ship_mode'
]

for col in text_col:
    orders[col] = orders[col].str.replace(' ', '_')

In [280]:
orders['payment_method'].value_counts()

payment_method
Upi                 33927
Cod                 33897
Credit_Card         33764
Net_Banking         16957
Debit_Card          16936
Cash_On_Delivery    16930
Unknown              2338
Name: count, dtype: int64

In [281]:
orders['ship_mode'].value_counts()

ship_mode
Same_Day          50530
Second_Class      25456
Standard_Class    25344
Standard          25214
First_Class       25088
Unknown            3117
Name: count, dtype: int64

In [282]:
orders[orders['sales_amount'] < 0]

Empty DataFrame
Columns: [order_id, order_date, customer_id, product_id, quantity, discount, payment_method, ship_mode, sales_amount]
Index: []

In [283]:
orders['sales_amount'].unique

<bound method Series.unique of 0         2423.32
1         2145.02
2          891.12
3         3328.70
4          580.50
           ...
155785     791.82
155793      96.33
155814    2687.08
155825    4282.15
155826     948.50
Name: sales_amount, Length: 154749, dtype: float64>

In [284]:
orders.duplicated().sum()

np.int64(0)

In [285]:
orders.isnull().sum()

order_id          0
order_date        0
customer_id       0
product_id        0
quantity          0
discount          0
payment_method    0
ship_mode         0
sales_amount      0
dtype: int64

In [286]:
orders.columns = orders.columns.str.title()

In [287]:
orders.head()

,Order_Id,Order_Date,Customer_Id,Product_Id,Quantity,Discount,Payment_Method,Ship_Mode,Sales_Amount
0,ORD-100000,2024-07-22,CUST-10001,PROD-151,4,0.00,Cash_On_Delivery,Same_Day,2423.32
1,ORD-100001,2024-10-12,CUST-10003,PROD-243,3,0.10,Cod,Standard,2145.02
2,ORD-100002,2024-02-28,CUST-10002,PROD-262,1,0.00,Cash_On_Delivery,Same_Day,891.12
3,ORD-100003,2024-12-21,CUST-10007,PROD-292,4,0.15,Cod,Same_Day,3328.70
4,ORD-100004,2024-04-26,CUST-10004,PROD-274,1,0.00,Cod,Second_Class,580.50

In [288]:
orders.shape

(154749, 9)

In [289]:
orders.describe()

                       Order_Date       Quantity       Discount   Sales_Amount
count                      154749  154749.000000  154749.000000  154749.000000
mean   2024-06-30 23:31:41.367117       3.001299       0.059840    1666.776473
min           2024-01-01 00:00:00       1.000000       0.000000      11.870000
25%           2024-04-01 00:00:00       2.000000       0.000000     637.720000
50%           2024-07-01 00:00:00       3.000000       0.000000    1321.780000
75%           2024-09-30 00:00:00       4.000000       0.100000    2430.020000
max           2024-12-31 00:00:00       5.000000       0.250000    5977.750000
std                           NaN       1.414782       0.075016    1291.206956

In [290]:
orders.info()

<class 'pandas.DataFrame'>
Index: 154749 entries, 0 to 155826
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Order_Id        154749 non-null  str
 1   Order_Date      154749 non-null  datetime64[us]
 2   Customer_Id     154749 non-null  str
 3   Product_Id      154749 non-null  str
 4   Quantity        154749 non-null  int64
 5   Discount        154749 non-null  float64
 6   Payment_Method  154749 non-null  str
 7   Ship_Mode       154749 non-null  str
 8   Sales_Amount    154749 non-null  float64
dtypes: datetime64[us](1), float64(2), int64(1), str(5)
memory usage: 11.8 MB

In [291]:
products.head()

,product_id,product_name,category,sub_category,unit_price,unit_cost
0,PROD-101,Mobile Phones Item 1,Electronics,Mobile Phones,810.42,372.39
1,PROD-102,Mobile Phones Item 2,Electronics,Mobile Phones,406.60,183.36
2,PROD-103,Mobile Phones Item 3,Electronics,Mobile Phones,919.57,434.21
3,PROD-104,Mobile Phones Item 4,Electronics,Mobile Phones,687.06,347.96
4,PROD-105,Mobile Phones Item 5,Electronics,Mobile Phones,849.83,477.72

In [292]:
products.tail()

,product_id,product_name,category,sub_category,unit_price,unit_cost
187,PROD-288,Outdoor Gear Item 4,Sports,Outdoor Gear,634.97,446.60
188,PROD-289,Outdoor Gear Item 5,Sports,Outdoor Gear,821.82,344.44
189,PROD-290,Outdoor Gear Item 6,sports,Outdoor Gear,861.37,627.33
190,PROD-291,Outdoor Gear Item 7,Sports,Outdoor Gear,559.78,400.94
191,PROD-292,Outdoor Gear Item 8,Sports,Outdoor Gear,979.03,466.20

In [293]:
products.shape

(192, 6)

In [294]:
products.describe()

        unit_price   unit_cost
count   192.000000  192.000000
mean    592.554531  344.781979
std     323.896714  208.107945
min      15.830000   11.220000
25%     331.672500  183.100000
50%     591.715000  341.310000
75%     850.070000  471.335000
max    1195.550000  851.040000

In [295]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 192 entries, 0 to 191
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    192 non-null    str
 1   product_name  192 non-null    str
 2   category      192 non-null    str
 3   sub_category  192 non-null    str
 4   unit_price    192 non-null    float64
 5   unit_cost     192 non-null    float64
dtypes: float64(2), str(4)
memory usage: 9.1 KB

In [296]:
products.isnull().sum()

product_id      0
product_name    0
category        0
sub_category    0
unit_price      0
unit_cost       0
dtype: int64

In [297]:
products.duplicated().sum()

np.int64(0)

In [298]:
products['product_name'].value_counts()

product_name
Mobile Phones Item 1    1
Mobile Phones Item 2    1
Mobile Phones Item 3    1
Mobile Phones Item 4    1
Mobile Phones Item 5    1
                       ..
Outdoor Gear Item 4     1
Outdoor Gear Item 5     1
Outdoor Gear Item 6     1
Outdoor Gear Item 7     1
Outdoor Gear Item 8     1
Name: count, Length: 192, dtype: int64

In [299]:
products['product_name'] = products['product_name'].str.replace(' ', '_')

In [300]:
products['product_name'].value_counts()

product_name
Mobile_Phones_Item_1    1
Mobile_Phones_Item_2    1
Mobile_Phones_Item_3    1
Mobile_Phones_Item_4    1
Mobile_Phones_Item_5    1
                       ..
Outdoor_Gear_Item_4     1
Outdoor_Gear_Item_5     1
Outdoor_Gear_Item_6     1
Outdoor_Gear_Item_7     1
Outdoor_Gear_Item_8     1
Name: count, Length: 192, dtype: int64

In [301]:
products['category'].value_counts()

category
Electronics       42
Beauty & Care     33
Home & Kitchen    31
Books             30
Clothing          26
Sports            22
beauty & care      3
home & kitchen     1
BOOKS              1
books              1
BEAUTY & CARE      1
sports             1
Name: count, dtype: int64

In [302]:
products['category'] = products['category'].str.title()
products['category'] = products['category'].str.replace(' ', '_')

In [303]:
products['category'].value_counts()

category
Electronics       42
Beauty_&_Care     37
Home_&_Kitchen    32
Books             32
Clothing          26
Sports            23
Name: count, dtype: int64

In [304]:
products['sub_category'].value_counts()

sub_category
Appliances           11
Fiction              11
Haircare             11
Makeup               11
Smartwatches         10
Accessories           9
Cookware              9
Skincare              9
Fitness Equipment     9
Mobile Phones         8
Headphones            8
Kids' Wear            8
Outdoor Gear          8
Laptops               7
Men's Wear            7
Bedding               7
Non-Fiction           7
Self-Help             7
Technical             7
Footwear              6
Fragrances            6
Sportswear            6
Women's Wear          5
Decor                 5
Name: count, dtype: int64

In [305]:
products['sub_category'] = products['sub_category'].str.replace(' ', '_')

In [306]:
products['sub_category'].value_counts()

sub_category
Appliances           11
Fiction              11
Haircare             11
Makeup               11
Smartwatches         10
Accessories           9
Cookware              9
Skincare              9
Fitness_Equipment     9
Mobile_Phones         8
Headphones            8
Kids'_Wear            8
Outdoor_Gear          8
Laptops               7
Men's_Wear            7
Bedding               7
Non-Fiction           7
Self-Help             7
Technical             7
Footwear              6
Fragrances            6
Sportswear            6
Women's_Wear          5
Decor                 5
Name: count, dtype: int64

In [307]:
products['unit_price'].unique

<bound method Series.unique of 0      810.42
1      406.60
2      919.57
3      687.06
4      849.83
        ...
187    634.97
188    821.82
189    861.37
190    559.78
191    979.03
Name: unit_price, Length: 192, dtype: float64>

In [308]:
products[products['unit_price'] < 0]

Empty DataFrame
Columns: [product_id, product_name, category, sub_category, unit_price, unit_cost]
Index: []

In [309]:
products['unit_cost'].unique

<bound method Series.unique of 0      372.39
1      183.36
2      434.21
3      347.96
4      477.72
        ...
187    446.60
188    344.44
189    627.33
190    400.94
191    466.20
Name: unit_cost, Length: 192, dtype: float64>

In [310]:
products[products['unit_cost'] < 0]

Empty DataFrame
Columns: [product_id, product_name, category, sub_category, unit_price, unit_cost]
Index: []

In [311]:
products.columns = products.columns.str.title()

In [312]:
products.columns

Index(['Product_Id', 'Product_Name', 'Category', 'Sub_Category', 'Unit_Price',
       'Unit_Cost'],
      dtype='str')

In [313]:
products.shape

(192, 6)

In [314]:
products.isnull().sum()

Product_Id      0
Product_Name    0
Category        0
Sub_Category    0
Unit_Price      0
Unit_Cost       0
dtype: int64

In [315]:
products.duplicated().sum()

np.int64(0)

In [316]:
products.head()

,Product_Id,Product_Name,Category,Sub_Category,Unit_Price,Unit_Cost
0,PROD-101,Mobile_Phones_Item_1,Electronics,Mobile_Phones,810.42,372.39
1,PROD-102,Mobile_Phones_Item_2,Electronics,Mobile_Phones,406.60,183.36
2,PROD-103,Mobile_Phones_Item_3,Electronics,Mobile_Phones,919.57,434.21
3,PROD-104,Mobile_Phones_Item_4,Electronics,Mobile_Phones,687.06,347.96
4,PROD-105,Mobile_Phones_Item_5,Electronics,Mobile_Phones,849.83,477.72

In [317]:
products.describe()

        Unit_Price   Unit_Cost
count   192.000000  192.000000
mean    592.554531  344.781979
std     323.896714  208.107945
min      15.830000   11.220000
25%     331.672500  183.100000
50%     591.715000  341.310000
75%     850.070000  471.335000
max    1195.550000  851.040000

In [318]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 192 entries, 0 to 191
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_Id    192 non-null    str
 1   Product_Name  192 non-null    str
 2   Category      192 non-null    str
 3   Sub_Category  192 non-null    str
 4   Unit_Price    192 non-null    float64
 5   Unit_Cost     192 non-null    float64
dtypes: float64(2), str(4)
memory usage: 9.1 KB

In [319]:
returns.head()

  return_id    order_id return_date          return_reason refund_status
0  RET-5000  ORD-217685  2024-09-12         Defective Item       pending
1  RET-5001  ORD-143237  2024-02-13  Item Not as Described      Rejected
2  RET-5002  ORD-200128  2024-06-29              defective       pending
3  RET-5003  ORD-156583  2024-07-03         Defective Item       Pending
4  RET-5004  ORD-120451  2024-10-17             Wrong Size       pending

In [320]:
returns.shape

(8542, 5)

In [321]:
returns.describe()

       return_id    order_id return_date return_reason refund_status
count       8542        8542        8542          8542          8542
unique      8542        8542         341             7             5
top     RET-5000  ORD-217685  2024-11-04  Changed Mind       Pending
freq           1           1          41          1257          1749

In [322]:
returns.info()

<class 'pandas.DataFrame'>
RangeIndex: 8542 entries, 0 to 8541
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   return_id      8542 non-null   str
 1   order_id       8542 non-null   str
 2   return_date    8542 non-null   str
 3   return_reason  8542 non-null   str
 4   refund_status  8542 non-null   str
dtypes: str(5)
memory usage: 333.8 KB

In [323]:
returns.columns

Index(['return_id', 'order_id', 'return_date', 'return_reason',
       'refund_status'],
      dtype='str')

In [324]:
returns.isnull().sum()

return_id        0
order_id         0
return_date      0
return_reason    0
refund_status    0
dtype: int64

In [325]:
returns.duplicated().sum()

np.int64(0)

In [326]:
returns['return_date'].dtype

In [327]:
returns['return_date'] = pd.to_datetime(returns['return_date'])

In [328]:
returns['return_date'].dtype

dtype('<M8[us]')

In [329]:
returns['return_reason'].value_counts()

return_reason
Changed Mind             1257
wrong item               1237
defective                1236
Defective Item           1225
Late Delivery            1210
Item Not as Described    1198
Wrong Size               1179
Name: count, dtype: int64

In [330]:
returns['return_reason'] = returns['return_reason'].str.title()
returns['return_reason'] = returns['return_reason'].str.replace(' ', '_')

In [331]:
returns['return_reason'].value_counts()

return_reason
Changed_Mind             1257
Wrong_Item               1237
Defective                1236
Defective_Item           1225
Late_Delivery            1210
Item_Not_As_Described    1198
Wrong_Size               1179
Name: count, dtype: int64

In [332]:
returns['refund_status'].value_counts()

refund_status
Pending      1749
pending      1723
processed    1700
Rejected     1692
Processed    1678
Name: count, dtype: int64

In [333]:
returns['refund_status'] = returns['refund_status'].str.title()

In [334]:
returns['refund_status'].value_counts()

refund_status
Pending      3472
Processed    3378
Rejected     1692
Name: count, dtype: int64

In [335]:
returns.columns = returns.columns.str.title()

In [336]:
returns.isnull().sum()

Return_Id        0
Order_Id         0
Return_Date      0
Return_Reason    0
Refund_Status    0
dtype: int64

In [337]:
returns.duplicated().sum()

np.int64(0)

In [338]:
returns.shape

(8542, 5)

In [339]:
returns.describe()

                      Return_Date
count                        8542
mean   2024-07-01 20:58:36.553500
min           2024-01-15 00:00:00
25%           2024-04-08 00:00:00
50%           2024-07-01 00:00:00
75%           2024-09-24 00:00:00
max           2024-12-20 00:00:00

In [340]:
returns.info()

<class 'pandas.DataFrame'>
RangeIndex: 8542 entries, 0 to 8541
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Return_Id      8542 non-null   str
 1   Order_Id       8542 non-null   str
 2   Return_Date    8542 non-null   datetime64[us]
 3   Return_Reason  8542 non-null   str
 4   Refund_Status  8542 non-null   str
dtypes: datetime64[us](1), str(4)
memory usage: 333.8 KB

In [341]:
customers.to_csv('customers_cleaned.csv', index=False)
orders.to_csv('orders_cleaned.csv', index=False)
products.to_csv('products_cleaned.csv', index=False)
returns.to_csv('returns_cleaned.csv', index=False)

In [342]:

from sqlalchemy import create_engine
import pandas as pd

username = "postgres"
password = 12345678
host = "localhost"
port = 5432
database = "sales_project"

engine = create_engine(
    f"postgresql+psycopg2://{'postgres'}:{12345678}@{'localhost'}:{5432}/{'sales_project'}"
)
print("succesfull")

succesfull

In [344]:
datasets = {
    "customers": customers,
    "orders": orders,
    "returns": returns,
    "products": products
}
print("succesfull")

succesfull

In [345]:
# Convert all column names to lowercase and replace spaces with underscores

customers.columns = customers.columns.str.strip().str.lower().str.replace(" ", "_")
orders.columns = orders.columns.str.strip().str.lower().str.replace(" ", "_")
returns.columns = returns.columns.str.strip().str.lower().str.replace(" ", "_")
products.columns = products.columns.str.strip().str.lower().str.replace(" ", "_")

In [346]:
customers.to_sql(
    name="customers",
    con=engine,
    if_exists="replace",
    index=False
)

orders.to_sql(
    name="orders",
    con=engine,
    if_exists="replace",
    index=False
)

returns.to_sql(
    name="returns",
    con=engine,
    if_exists="replace",
    index=False
)

products.to_sql(
    name="products",
    con=engine,
    if_exists="replace",
    index=False
)

print("All 4 datasets uploaded successfully!")

All 4 datasets uploaded successfully!